framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - '%kernel.project_dir%/assets'
            - '%kernel.project_dir%/node_modules' # Important!
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
