controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index

 

quiz_new:
    path: /quiz/new
    controller: App\Controller\QuizController::new

