controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth_oauth_check:
    path: /auth/oauth/check


video_rate:
    path: /video/{id}/rate
    controller: App\Controller\VideoController::rate
    methods: [GET, POST]  

offres_liste:
    path: /offres
    controller: App\Controller\OffreController::index

offres_ajout:
    path: /offres/ajouter  # ✅ Modifier le chemin pour éviter la duplication
    controller: App\Controller\OffreController::ajouter

# config/routes.yaml
app_dashboard:
    path: /dashboard
    controller: App\Controller\UserController::dashboard
    methods: GET