# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\GoogleCalendarService:
        arguments:
            $requestStack: '@request_stack'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'